on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/db-pgsql.yml'
      - 'composer.json'
      - 'phpunit.xml.dist'

  push:
    branches: ['master']
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/db-pgsql.yml'
      - 'composer.json'
      - 'phpunit.xml.dist'

name: db-pgsql

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
jobs:
  build:
    name: PHP ${{ matrix.php }}

    env:
      extensions: pdo_pgsql

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - 8.1
          - 8.2
          - 8.3
          - 8.4
          - 8.5

    services:
      postgres:
        image: postgres:18@sha256:8d526a5b3f29da6d7835ebdab8e3393958e09608e21fd848c32b9187b4a1e1ce
        env:
          POSTGRES_DB: ar-test
          POSTGRES_USER: yii
          POSTGRES_PASSWORD: q1w2e3r4
        ports:
          - 5432:5432
        options: --name=postgres --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout.
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          coverage: pcov

      - name: Remove unused dependencies of DB drivers
        run: composer remove --dev yiisoft/db-sqlite yiisoft/db-mysql yiisoft/db-mssql yiisoft/db-oracle

      - name: Install required yiisoft/db and yiisoft/db-pgsql
        uses: yiisoft/actions/install-packages@master
        with:
          packages: >-
            ['db', 'db-pgsql']

      - name: Run tests with phpunit.
        run: vendor/bin/phpunit --testsuite=Pgsql --coverage-clover=coverage.xml --colors=always --display-warnings --display-deprecations

      - name: Upload coverage to Codecov.
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
