on:
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/mutation.yml'
      - 'composer.json'

  push:
    branches: ['master']
    paths:
      - 'src/**'
      - '.github/workflows/mutation.yml'
      - 'composer.json'

name: Mutation

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
jobs:
  mutation:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    env:
      extensions: pdo_pgsql

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        php:
          - 8.5

    services:
      postgres:
        image: postgres:18@sha256:8d526a5b3f29da6d7835ebdab8e3393958e09608e21fd848c32b9187b4a1e1ce
        env:
          POSTGRES_DB: ar-test
          POSTGRES_USER: yii
          POSTGRES_PASSWORD: q1w2e3r4
        ports:
          - 5432:5432
        options: --name=postgres --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout.
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: memory_limit=-1
          coverage: pcov

      - name: Remove unused dependencies of DB drivers
        run: composer remove --dev yiisoft/db-sqlite yiisoft/db-mysql yiisoft/db-mssql yiisoft/db-oracle

      - name: Install Composer dependencies
        uses: ramsey/composer-install@a8d0d959dab41457692a5e2041bd9b757a119e3f # 3.2.1

      - name: Install required yiisoft/db and yiisoft/db-pgsql
        uses: yiisoft/actions/install-packages@master
        with:
          packages: >-
            ['db', 'db-pgsql']

      - name: Run infection.
        run: |
          vendor/bin/infection --ignore-msi-with-no-mutations --test-framework-options="--testsuite=Pgsql"
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
