name: Update README packages

on:
  pull_request:
    paths:
      - '.github/workflows/update-readme-packages.yml'
      - 'composer.json'

permissions:
  contents: read

jobs:
  update-readme:
    uses: yiisoft/actions/.github/workflows/update-readme-packages.yml@ab62d6b3b0e0cff6c9724ec5a395bedb41c639a2
    secrets:
      TOKEN: ${{ secrets.YIISOFT_GITHUB_TOKEN }}
