name: Update README packages

on:
  pull_request:
    paths:
      - '.github/workflows/update-readme-packages.yml'
      - 'composer.json'

permissions:
  contents: write

jobs:
  update-readme:
    uses: yiisoft/actions/.github/workflows/update-readme-packages.yml@update-readme-packages
    secrets:
      GITHUB_TOKEN: ${{ secrets.YIISOFT_GITHUB_TOKEN }}
